# Generated by Django 5.2.16 on 2026-08-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show')], default='movie', max_length=5)),
                ('tmdb_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('poster_path', models.CharField(blank=True, max_length=255)),
                ('backdrop_path', models.CharField(blank=True, max_length=255)),
                ('runtime', models.PositiveIntegerField(blank=True, help_text='Minutes', null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='TMDB vote average, 0-10', max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
