# Generated by Django 5.2.16 on 2026-08-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_fix_empty_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='trailer_key',
            field=models.CharField(blank=True, help_text='YouTube video key for the trailer, from TMDB', max_length=32),
        ),
    ]
